[tasks.test]
run = [
  "copier copy --data-file test-input.yml --vcs-ref=HEAD . test",
  "cd test && mise run github-actions-lint",
  "cd test && mise run renovate-check",
  "rm -rf test"
]
description = "Run copy locally with test input"
