name: trivy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy:
    name: Trivy (license scan)
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Download Go modules
        run: go mod download

      - name: Run trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scan-type: 'fs'
          scanners: 'license'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          severity: 'UNKNOWN,MEDIUM,HIGH'
          trivy-config: trivy.yaml
