name: trivy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy:
    name: Trivy (license scan)
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod

      - name: Download Go modules
        run: go mod download

      - name: Run trivy
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scan-type: 'fs'
          scanners: 'license'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          severity: 'UNKNOWN,MEDIUM,HIGH'
          trivy-config: trivy.yaml
