repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        language: system
        entry: mise run fmt
        types: [go]
        pass_filenames: false

      - id: go-lint
        name: go lint
        language: system
        entry: mise run lint
        types: [go]
        pass_filenames: false

      - id: renovate-check
        name: renovate config validator
        language: system
        entry: mise run renovate-check
        files: ^renovate\.json$
        pass_filenames: false
